-- MySQL Script generated by MySQL Workbench
-- qua 14 ago 2024 20:59:16
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema escoteiros
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema escoteiros
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `escoteiros` ;
USE `escoteiros` ;

-- -----------------------------------------------------
-- Table `escoteiros`.`Contato`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Contato` (
  `idContato` INT NOT NULL AUTO_INCREMENT,
  `telefone` VARCHAR(11) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idContato`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Pessoa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Pessoa` (
  `cpf` VARCHAR(11) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `dataNasc` DATE NOT NULL,
  `endereco` VARCHAR(45) NOT NULL,
  `Contato_idContato` INT NOT NULL,
  PRIMARY KEY (`cpf`, `nome`, `Contato_idContato`),
  INDEX `fk_Pessoa_Contato1_idx` (`Contato_idContato` ASC) VISIBLE,
  CONSTRAINT `fk_Pessoa_Contato1`
    FOREIGN KEY (`Contato_idContato`)
    REFERENCES `escoteiros`.`Contato` (`idContato`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Jovem`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Jovem` (
  `idJovem` VARCHAR(11) NOT NULL,
  `alergias` VARCHAR(300) NULL,
  `TipoSanguineo_tipo` VARCHAR(4) NOT NULL,
  `recomendacaoPessoa` TINYINT NULL,
  PRIMARY KEY (`idJovem`),
  CONSTRAINT `fk_Jovem_Pessoa`
    FOREIGN KEY (`idJovem`)
    REFERENCES `escoteiros`.`Pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Responsavel` (
  `idResponsavel` VARCHAR(45) NOT NULL,
  `parentesco` VARCHAR(10) NOT NULL,
  PRIMARY KEY (`idResponsavel`),
  CONSTRAINT `fk_Responsavel_Pessoa`
    FOREIGN KEY (`idResponsavel`)
    REFERENCES `escoteiros`.`Pessoa` (`cpf`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Jovem_Responsavel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Jovem_Responsavel` (
  `idJovem` VARCHAR(11) NOT NULL,
  `idResponsavel` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idJovem`, `idResponsavel`),
  INDEX `fk_Jovem_Responsavel_2_idx` (`idResponsavel` ASC) VISIBLE,
  CONSTRAINT `fk_Jovem_Responsavel_1`
    FOREIGN KEY (`idJovem`)
    REFERENCES `escoteiros`.`Jovem` (`idJovem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jovem_Responsavel_2`
    FOREIGN KEY (`idResponsavel`)
    REFERENCES `escoteiros`.`Responsavel` (`idResponsavel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`TipoSanguineo`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`TipoSanguineo` (
  `tipo` VARCHAR(4) NOT NULL,
  `Jovem_idJovem` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`tipo`, `Jovem_idJovem`),
  UNIQUE INDEX `tipo_UNIQUE` (`tipo` ASC) VISIBLE,
  CONSTRAINT `fk_TipoSanguineo_Jovem1`
    FOREIGN KEY ()
    REFERENCES `escoteiros`.`Jovem` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`ParticipacaoAtividades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`ParticipacaoAtividades` (
  `idParticipacaoAtividades` INT NOT NULL,
  `data` DATE NOT NULL,
  `descricao` TEXT(300) NOT NULL,
  `Jovem_idJovem` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idParticipacaoAtividades`, `Jovem_idJovem`),
  INDEX `fk_ParticipacaoAtividades_Jovem1_idx` (`Jovem_idJovem` ASC) VISIBLE,
  UNIQUE INDEX `idParticipacaoAtividades_UNIQUE` (`idParticipacaoAtividades` ASC) VISIBLE,
  CONSTRAINT `fk_ParticipacaoAtividades_Jovem1`
    FOREIGN KEY (`Jovem_idJovem`)
    REFERENCES `escoteiros`.`Jovem` (`idJovem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Progressao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Progressao` (
  `idProgressao` INT NOT NULL,
  `dataProgressao` VARCHAR(45) NOT NULL,
  `descricao` VARCHAR(45) NOT NULL,
  `Jovem_idJovem` VARCHAR(11) NOT NULL,
  PRIMARY KEY (`idProgressao`, `Jovem_idJovem`),
  INDEX `fk_Progressao_Jovem1_idx` (`Jovem_idJovem` ASC) VISIBLE,
  UNIQUE INDEX `idProgressao_UNIQUE` (`idProgressao` ASC) VISIBLE,
  CONSTRAINT `fk_Progressao_Jovem1`
    FOREIGN KEY (`Jovem_idJovem`)
    REFERENCES `escoteiros`.`Jovem` (`idJovem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`areaDeConhecimento`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`areaDeConhecimento` (
  `idareaDeConhecimento` INT NOT NULL,
  `conhecimento` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idareaDeConhecimento`),
  UNIQUE INDEX `conhecimento_UNIQUE` (`conhecimento` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Especialidade` (
  `idEspecialidade` INT NOT NULL,
  `nomeEspecialidade` VARCHAR(45) NOT NULL,
  `areaConhecimento` VARCHAR(45) NOT NULL,
  `numeroRequisitosTotais` INT NOT NULL,
  `areaDeConhecimento_idareaDeConhecimento` INT NOT NULL,
  `nivel` INT NULL,
  PRIMARY KEY (`idEspecialidade`, `areaDeConhecimento_idareaDeConhecimento`),
  INDEX `fk_Especialidade_areaDeConhecimento1_idx` (`areaDeConhecimento_idareaDeConhecimento` ASC) VISIBLE,
  CONSTRAINT `fk_Especialidade_areaDeConhecimento1`
    FOREIGN KEY (`areaDeConhecimento_idareaDeConhecimento`)
    REFERENCES `escoteiros`.`areaDeConhecimento` (`idareaDeConhecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
COMMENT = ' Nome\n   - Área de conhecimento\n   - Número de requisitos totais';


-- -----------------------------------------------------
-- Table `escoteiros`.`NivelEspecialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`NivelEspecialidade` (
  `nivel` VARCHAR(45) NULL,
  `requisitosCumpridos` VARCHAR(45) NULL)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Insignia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Insignia` (
  `id` INT NOT NULL,
  `nomeInsignia` VARCHAR(45) NULL,
  `descricao` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`DistintivoProgressao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`DistintivoProgressao` (
  `idDistintivoProgressao` INT NOT NULL,
  `nomeDistintivo` VARCHAR(45) NOT NULL,
  `descriçãoRequisitos` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idDistintivoProgressao`),
  UNIQUE INDEX `nomeDistintivo_UNIQUE` (`nomeDistintivo` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Jovem_has_DistintivoProgressao`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Jovem_has_DistintivoProgressao` (
  `Jovem_idJovem` VARCHAR(11) NOT NULL,
  `DistintivoProgressao_idDistintivoProgressao` INT NOT NULL,
  PRIMARY KEY (`Jovem_idJovem`, `DistintivoProgressao_idDistintivoProgressao`),
  INDEX `fk_Jovem_has_DistintivoProgressao_DistintivoProgressao1_idx` (`DistintivoProgressao_idDistintivoProgressao` ASC) VISIBLE,
  INDEX `fk_Jovem_has_DistintivoProgressao_Jovem1_idx` (`Jovem_idJovem` ASC) VISIBLE,
  CONSTRAINT `fk_Jovem_has_DistintivoProgressao_Jovem1`
    FOREIGN KEY (`Jovem_idJovem`)
    REFERENCES `escoteiros`.`Jovem` (`idJovem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jovem_has_DistintivoProgressao_DistintivoProgressao1`
    FOREIGN KEY (`DistintivoProgressao_idDistintivoProgressao`)
    REFERENCES `escoteiros`.`DistintivoProgressao` (`idDistintivoProgressao`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Jovem_has_Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Jovem_has_Especialidade` (
  `Jovem_idJovem` VARCHAR(11) NOT NULL,
  `Especialidade_idEspecialidade` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Jovem_idJovem`, `Especialidade_idEspecialidade`),
  INDEX `fk_Jovem_has_Especialidade_Especialidade1_idx` (`Especialidade_idEspecialidade` ASC) VISIBLE,
  INDEX `fk_Jovem_has_Especialidade_Jovem1_idx` (`Jovem_idJovem` ASC) VISIBLE,
  UNIQUE INDEX `Jovem_idJovem_UNIQUE` (`Jovem_idJovem` ASC) VISIBLE,
  CONSTRAINT `fk_Jovem_has_Especialidade_Jovem1`
    FOREIGN KEY (`Jovem_idJovem`)
    REFERENCES `escoteiros`.`Jovem` (`idJovem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jovem_has_Especialidade_Especialidade1`
    FOREIGN KEY (`Especialidade_idEspecialidade`)
    REFERENCES `escoteiros`.`Especialidade` (`idEspecialidade`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Jovem_has_InsigniaInteresseEspecial`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Jovem_has_InsigniaInteresseEspecial` (
  `Jovem_idJovem` VARCHAR(11) NOT NULL,
  `InsigniaInteresseEspecial_idInsigniaInteresseEspecial` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Jovem_idJovem`, `InsigniaInteresseEspecial_idInsigniaInteresseEspecial`),
  INDEX `fk_Jovem_has_InsigniaInteresseEspecial_InsigniaInteresseEsp_idx` (`InsigniaInteresseEspecial_idInsigniaInteresseEspecial` ASC) VISIBLE,
  INDEX `fk_Jovem_has_InsigniaInteresseEspecial_Jovem1_idx` (`Jovem_idJovem` ASC) VISIBLE,
  CONSTRAINT `fk_Jovem_has_InsigniaInteresseEspecial_Jovem1`
    FOREIGN KEY (`Jovem_idJovem`)
    REFERENCES `escoteiros`.`Jovem` (`idJovem`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Jovem_has_InsigniaInteresseEspecial_InsigniaInteresseEspec1`
    FOREIGN KEY (`InsigniaInteresseEspecial_idInsigniaInteresseEspecial`)
    REFERENCES `escoteiros`.`Insignia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Requisitos_Insignia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Requisitos_Insignia` (
  `idRequisitos_Insignia` INT NOT NULL,
  `Insignia_id` INT NOT NULL,
  PRIMARY KEY (`idRequisitos_Insignia`, `Insignia_id`),
  INDEX `fk_Requisitos_Insignia_Insignia1_idx` (`Insignia_id` ASC) VISIBLE,
  CONSTRAINT `fk_Requisitos_Insignia_Insignia1`
    FOREIGN KEY (`Insignia_id`)
    REFERENCES `escoteiros`.`Insignia` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `escoteiros`.`Requisito_Especialidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `escoteiros`.`Requisito_Especialidade` (
  `Especialidade_idEspecialidade` INT NOT NULL,
  `Especialidade_areaDeConhecimento_idareaDeConhecimento` INT NOT NULL,
  PRIMARY KEY (`Especialidade_idEspecialidade`, `Especialidade_areaDeConhecimento_idareaDeConhecimento`),
  CONSTRAINT `fk_Requisito_Especialidade_Especialidade1`
    FOREIGN KEY (`Especialidade_idEspecialidade` , `Especialidade_areaDeConhecimento_idareaDeConhecimento`)
    REFERENCES `escoteiros`.`Especialidade` (`idEspecialidade` , `areaDeConhecimento_idareaDeConhecimento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
